/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package RaspberryPiHTTPServer;

public class ServerRun {
    public static int port = 8080;
    public static void main(String[] args) {
        HTTPServer httpServer = new HTTPServer();
		httpServer.start(port);
    }
}
